/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "MapTile_proxy.h"
#import "CacheTileDataSource_proxy.h"
#import "TileData_proxy.h"

/**
 * A tile data source that loads tiles from another tile data source<br>
 * and caches them in memory as compressed images. This cache is not persistent, tiles <br>
 * will be cleared once the application closes. Default cache capacity is 6MB.
 */
__attribute__ ((visibility("default"))) @interface NTCompressedCacheTileDataSource : NTCacheTileDataSource
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a CompressedCacheTileDataSource object from tile data source.<br>
 * @param dataSource The datasource to be cached.
 */
-(id)initWithDataSource: (NTTileDataSource*)dataSource;
-(NTTileData*)loadTile: (NTMapTile*)mapTile;
-(unsigned int)getCapacity;
-(void)setCapacity: (unsigned int)capacity;
-(void)clear;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

