/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "PackageManager_proxy.h"

/**
 * Base class for package manager that connects to Nutiteq online services.
 */
__attribute__ ((visibility("default"))) @interface NTNutiteqPackageManagerBase : NTPackageManager
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a PackageManager object, given application context and data folder.<br>
 * The data folder must exist before creating a new package manager and it is assumed to be persistent.<br>
 * Note: the package manager must be explicitly started using start() method!<br>
 * @param source Name of the package source. Currently "nutiteq.mbstreets" source is available<br>
 * @param dataFolder The folder where downloaded packages are kept. It must exist and must be writable.<br>
 * @param deviceId Device-specific id
 */
-(id)initWithSource: (NSString*)source dataFolder: (NSString*)dataFolder deviceId: (NSString*)deviceId;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

