#ifndef _NUTI_H_
#define _NUTI_H_

#import "Options_proxy.h"

#import "MapBounds_proxy.h"
#import "MapEnvelope_proxy.h"
#import "MapPos_proxy.h"
#import "ScreenPos_proxy.h"
#import "ScreenBounds_proxy.h"
#import "MapRange_proxy.h"
#import "MapTile_proxy.h"
#import "MapVec_proxy.h"
#import "TileData_proxy.h"

#import "AssetTileDataSource_proxy.h"
#import "CompressedCacheTileDataSource_proxy.h"
#import "HTTPTileDataSource_proxy.h"
#import "MBTilesTileDataSource_proxy.h"
#import "NutiteqOnlineTileDataSource_proxy.h"
#import "OnlineNMLModelLODTreeDataSource_proxy.h"
#import "SqliteNMLModelLODTreeDataSource_proxy.h"
#import "PersistentCacheTileDataSource_proxy.h"
#import "LocalVectorDataSource_proxy.h"
#import "OGRVectorDataSource_proxy.h"

#import "LineGeometry_proxy.h"
#import "PointGeometry_proxy.h"
#import "PolygonGeometry_proxy.h"
#import "DouglasPeuckerGeometrySimplifier_proxy.h"

#import "Frustum_proxy.h"
#import "Bitmap_proxy.h"
#import "Color_proxy.h"
#import "MapTileQuadTreeNode_proxy.h"
#import "ViewState_proxy.h"

#import "Layers_proxy.h"
#import "NMLModelLODTreeLayer_proxy.h"
#import "RasterTileLayer_proxy.h"
#import "TileLoadListener_proxy.h"
#import "VectorLayer_proxy.h"
#import "VectorTileLayer_proxy.h"
#import "NutiteqOnlineVectorTileLayer_proxy.h"

#import "EPSG3857_proxy.h"

#import "CullState_proxy.h"

#import "BalloonPopupStyleBuilder_proxy.h"
#import "BalloonPopupStyle_proxy.h"
#import "LabelStyleBuilder_proxy.h"
#import "LabelStyle_proxy.h"
#import "LineStyleBuilder_proxy.h"
#import "LineStyle_proxy.h"
#import "MarkerStyleBuilder_proxy.h"
#import "MarkerStyle_proxy.h"
#import "PointStyleBuilder_proxy.h"
#import "PointStyle_proxy.h"
#import "Polygon3DStyleBuilder_proxy.h"
#import "Polygon3DStyle_proxy.h"
#import "PolygonStyleBuilder_proxy.h"
#import "PolygonStyle_proxy.h"
#import "PopupStyleBuilder_proxy.h"
#import "PopupStyle_proxy.h"
#import "TextStyleBuilder_proxy.h"
#import "TextStyle_proxy.h"
#import "StyleSelector_proxy.h"
#import "StyleSelectorBuilder_proxy.h"

#import "ui/MapViewController.h"
#import "MapClickInfo_proxy.h"
#import "MapEventListener_proxy.h"
#import "VectorElementClickInfo_proxy.h"
#import "VectorElementsClickInfo_proxy.h"

#import "AssetUtils_proxy.h"
#import "BitmapUtils_proxy.h"
#import "Log_proxy.h"

#import "BalloonPopup_proxy.h"
#import "Label_proxy.h"
#import "Line_proxy.h"
#import "Marker_proxy.h"
#import "NMLModel_proxy.h"
#import "NMLModelLODTree_proxy.h"
#import "Point_proxy.h"
#import "Polygon3D_proxy.h"
#import "Polygon_proxy.h"
#import "Popup_proxy.h"
#import "Text_proxy.h"

#import "MBVectorTileDecoder_proxy.h"
#import "MBVectorTileStyleSet_proxy.h"

#import "wrappedcommons/LegacyWrappers.h"

#endif
