/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "UnsignedCharVector_proxy.h"

/**
 * A wrapper class for tile data.
 */
__attribute__ ((visibility("default"))) @interface NTTileData : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a TileData object from a data blob.<br>
 * @param data The source tile data.
 */
-(id)initWithData: (NTUnsignedCharVector*)data;
/**
 * Returns the maximum age of the tile data, tile data will expire after that point.<br>
 * @return Tile data maximum age in milliseconds, or -1 if the data does not expire.
 */
-(long long)getMaxAge;
/**
 * Sets the maximum age of tile data, tile data will expire after that point.<br>
 * 
 */
-(void)setMaxAge: (long long)age;
/**
 * Returns tile data as a byte vector.<br>
 * @return Tile data as a byte vector.
 */
-(NTUnsignedCharVector*)getData;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

