/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "MapTile_proxy.h"
#import "TileDataSource_proxy.h"
#import "TileData_proxy.h"

/**
 * A tile data source that combines two data sources (usually offline and online) and selects tiles<br>
 * based on zoom level. All requests below specified zoom level are directed to the first data source<br>
 * and all requests at or above specified zoom level are directed to the second data source.
 */
__attribute__ ((visibility("default"))) @interface NTCombinedTileDataSource : NTTileDataSource
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a combined tile data source object.<br>
 * @param dataSource1 First data source that is used if requested tile is below given zoomLevel.<br>
 * @param dataSource2 Second data source that is used if requested tile is at or above given zoomLevel.<br>
 * @param zoomLevel Threshold zoom level value.
 */
-(id)initWithDataSource1: (NTTileDataSource*)dataSource1 dataSource2: (NTTileDataSource*)dataSource2 zoomLevel: (int)zoomLevel;
-(NTTileData*)loadTile: (NTMapTile*)tile;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

