/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTMapPos.h"
#import "NTScreenPos.h"
#import "NTMapTile.h"
#import "NTTileData.h"
#import "NTMapPosVector.h"
#import "NTScreenPosVector.h"
#import "NTTileDataSource.h"
#import "NTProjection.h"
#import "NTBitmap.h"
#import "NTScreenPosVector.h"
#import "NTMapPosVector.h"

/**
 * Tile data source that uses given bitmap with two, three or four control points define a raster overlay.<br>
 * Note: if two points are given, conformal transformation is calculated. If three points are given, affine transformation is calculated. In case of four points, perspective transformation is used.
 */
__attribute__ ((visibility("default"))) @interface NTBitmapOverlayRasterTileDataSource : NTTileDataSource
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a new bitmap overlay data source.<br>
 * @param minZoom The minimum zoom for generated tiles.<br>
 * @param maxZoom The maximum zoom for generated tiles.<br>
 * @param bitmap The bitmap to use as an overlay.<br>
 * @param projection The projection definining coordinate system of the control points.<br>
 * @param mapPoses The geographical control points. The list must contain either 2, 3 or 4 points.<br>
 * @param bitmapPoses The pixel coordinates in the bitmap corresponding to geographical control points. The number of coordinates must be equal to the number of control points in mapPoses list.
 */
-(id)initWithMinZoom: (int)minZoom maxZoom: (int)maxZoom bitmap: (NTBitmap*)bitmap projection: (NTProjection*)projection mapPoses: (NTMapPosVector*)mapPoses bitmapPoses: (NTScreenPosVector*)bitmapPoses;
-(NTTileData*)loadTile: (NTMapTile*)mapTile;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

