/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTUnsignedCharVector.h"

/**
 * CartoCSS style definition for vector tiles.
 */
__attribute__ ((visibility("default"))) @interface NTCartoCSSStyleSet : NSObject
{
  void *swigCPtr;
  BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs a style from CartoCSS string.<br>
 * @param cartoCSS The CartoCSS string defining point styling.
 */
-(id)initWithCartoCSS: (NSString*)cartoCSS;
/**
 * Constructs a style from CartoCSS string and asset data.<br>
 * @param cartoCSS The CartoCSS string defining point styling.<br>
 * 
 */
-(id)initWithCartoCSS: (NSString*)cartoCSS styleSetData: (NTUnsignedCharVector*)styleSetData;
/**
 * Returns the CartoCSS string used for the style.<br>
 * @return The CartoCSS string used for the style.
 */
-(NSString*)getCartoCSS;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

