/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTUnsignedCharVector.h"
#import "NTPointStyleBuilder.h"
#import "NTLineStyleBuilder.h"
#import "NTPolygonStyleBuilder.h"
#import "NTMarkerStyleBuilder.h"

/**
 * A CartoCSS style parser. Geometry and marker styles can be parsed from simple human-readable format.<br>
 * Only a subset of the full CartoCSS tags are supported. Also, some Nutiteq-specific tags are added not included<br>
 * in original CartoCSS specification.<br>
 * Note: parsers return style builder objects instead of style objects.<br>
 * This allows easy customization (overriding) of some parameters in the code.
 */
__attribute__ ((visibility("default"))) @interface NTCartoCSSParser : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Read point style parameters from CartoCSS description. The following tags are supported:<br>
 * point-size, point-fill, point-opacity, point-file.<br>
 * @param cartoCSS The CartoCSS to parse. For example, "point-size: 20.5; point-fill:#f8f"<br>
 * @return Point style builder object with parameters set from the specified CartoCSS.
 */
+(NTPointStyleBuilder*)createPointStyleBuilder: (NSString*)cartoCSS;
/**
 * Read line style parameters from CartoCSS description. The following tags are supported:<br>
 * line-width, line-fill, line-opacity, line-join, line-cap, line-dasharray.<br>
 * @param cartoCSS The CartoCSS to parse. For example, "line-fill:#f0f; line-cap:round, line-dasharray:5,0.5"<br>
 * @return Line style builder object with parameters set from the specified CartoCSS.
 */
+(NTLineStyleBuilder*)createLineStyleBuilder: (NSString*)cartoCSS;
/**
 * Read polygon style parameters from CartoCSS description. The following tags are supported:<br>
 * polygon-fill, polygon-opacity.<br>
 * @param cartoCSS The CartoCSS to parse. For example, "polygon-fill:#ff00ff; polygon-opacity:0.3"<br>
 * @return Polygon style builder object with parameters set from the specified CartoCSS.
 */
+(NTPolygonStyleBuilder*)createPolygonStyleBuilder: (NSString*)cartoCSS;
/**
 * Read marker style parameters from CartoCSS description. The following tags are supported:<br>
 * marker-width, marker-fill, marker-opacity, marker-file, allow-overlap.<br>
 * @param cartoCSS The CartoCSS to parse. For example, "marker-size:30; marker-file:url('//assets/marker.png')"<br>
 * @return Marker style builder object with parameters set from the specified CartoCSS.
 */
+(NTMarkerStyleBuilder*)createMarkerStyleBuilder: (NSString*)cartoCSS;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

