/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTMapPos.h"
#import "NTVectorElement.h"
#import "NTVectorElementVector.h"

/**
 * A special callback interface for building cluster elements from set of existing vector element.
 */
__attribute__ ((visibility("default"))) @interface NTClusterElementBuilder : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Builds new cluster element given position and list of vector elements.<br>
 * @param mapPos The position of the cluster element.<br>
 * @param elements The list of elements that defines the cluster.<br>
 * @return The created cluster element.
 */
-(NTVectorElement*)buildClusterElement: (NTMapPos*)mapPos elements: (NTVectorElementVector*)elements;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

