/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTMultiGeometry.h"
#import "NTGeometryCollectionStyle.h"
#import "NTVectorElement.h"

/**
 * A collection of multiple geometries that can be displayed on the map.
 */
__attribute__ ((visibility("default"))) @interface NTGeometryCollection : NTVectorElement
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

+(NTGeometryCollection*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a new GeometryCollection object from multigeometry and style.<br>
 * @param geometry The multigeometry containing possibly points, lines, polygons.<br>
 * @param style The style defining multigeometry rendering.
 */
-(id)initWithGeometry: (NTMultiGeometry*)geometry style: (NTGeometryCollectionStyle*)style;
-(NTMultiGeometry*)getGeometry;
/**
 * Sets the geometry for this geometry collection.<br>
 * @param geometry The new geometry object.
 */
-(void)setGeometry: (NTMultiGeometry*)geometry;
/**
 * Returns the style of this geometry collection.<br>
 * @return The style that defines multigeometry rendering.
 */
-(NTGeometryCollectionStyle*)getStyle;
/**
 * Sets the style for this geometry collection.<br>
 * @return The new style that defines defines multigeometry rendering.
 */
-(void)setStyle: (NTGeometryCollectionStyle*)style;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
-(NSString*)swigGetClassName;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

