/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTGeometryCollectionStyle.h"
#import "NTPointStyle.h"
#import "NTLineStyle.h"
#import "NTPolygonStyle.h"
#import "NTStyleBuilder.h"

/**
 * A builder class for GeometryCollectionStyle.
 */
__attribute__ ((visibility("default"))) @interface NTGeometryCollectionStyleBuilder : NTStyleBuilder
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 */
+(NTGeometryCollectionStyleBuilder*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a GeometryCollectionStyleBuilder object with all parameters set to defaults.
 */
-(id)init;
/**
 * Returns the point style.<br>
 * @return The point style.
 */
-(NTPointStyle*)getPointStyle;
/**
 * Sets the style that will be used for drawing points. The default is null style.<br>
 * @param pointStyle The new point style.
 */
-(void)setPointStyle: (NTPointStyle*)pointStyle;
/**
 * Returns the line style.<br>
 * @return The line style.
 */
-(NTLineStyle*)getLineStyle;
/**
 * Sets the style that will be used for drawing lines. The default is null style.<br>
 * @param lineStyle The new line style.
 */
-(void)setLineStyle: (NTLineStyle*)lineStyle;
/**
 * Returns the polygon style.<br>
 * @return The polygon style.
 */
-(NTPolygonStyle*)getPolygonStyle;
/**
 * Sets the style that will be used for drawing polygons. The default is null style.<br>
 * @param polygonStyle The new polygon style.
 */
-(void)setPolygonStyle: (NTPolygonStyle*)polygonStyle;
/**
 * Builds a new instance of the GeometryCollectionStyle object using previously set parameters.<br>
 * @return A new GeometryCollectionStyle object.
 */
-(NTGeometryCollectionStyle*)buildStyle;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

