/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTGeometry.h"
#import "NTProjection.h"

/**
 * A GeoJSON parser.<br>
 * Only Geometry objects are supported, Features and FeatureCollections are not supported.
 */
__attribute__ ((visibility("default"))) @interface NTGeoJSONGeometryReader : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a new GeoJSONGeometryReader object.
 */
-(id)init;
/**
 * Returns the current target projection. If target projection is set, all geometry<br>
 * coordinates will be converted from WGS84 to target projection coordinate system.<br>
 * @return The current target projection or null.
 */
-(NTProjection*)getTargetProjection;
/**
 * Sets the current target projection. If target projection is set, all geometry<br>
 * coordinates will be converted from WGS84 to target projection coordinate system.<br>
 * @param proj The new target projection or null.
 */
-(void)setTargetProjection: (NTProjection*)proj;
/**
 * Reads geometry from the specified GeoJSON string.<br>
 * @param geoJSON The GeoJSON string to read.<br>
 * @return The geometry read from the string. Null if reading failed.
 */
-(NTGeometry*)readGeometry: (NSString*)geoJSON;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

