/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTGeometry.h"

/**
 * A GeoJSON writer. Generates human-readable GeoJSON representation of the geometry.<br>
 * Supports both 2D and 3D coordinate serialization.
 */
__attribute__ ((visibility("default"))) @interface NTGeoJSONGeometryWriter : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a new GeoJSONGeometryWriter object with default settings.
 */
-(id)init;
/**
 * Returns the state of Z coordinate serialization.<br>
 * @return True if Z coordinate is stored in GeoJSON output, false otherwise. The default is false.
 */
-(BOOL)getZ;
/**
 * Sets the state of Z coordinate serialization.<br>
 * @param z True when Z coordinate should be serialized, false otherwise.
 */
-(void)setZ: (BOOL)z;
/**
 * Creates a GeoJSON string corresponding to the specified geometry.<br>
 * @param geometry The geometry to write.<br>
 * @return The corresponding GeoJSON string.
 */
-(NSString*)writeGeometry: (NTGeometry*)geometry;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

