/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

__attribute__ ((visibility("default"))) @interface NTGLUtils : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
+(unsigned long)getMAX_VERTEXBUFFER_SIZE;
+(void)checkGLError: (NSString*)place;
+(BOOL)hasGLExtension: (NSString*)extension;
+(void)loadExtensions;
+(BOOL)isTextureFilterAnisotropic;
+(BOOL)isTextureNPOTRepeat;
+(BOOL)isTextureNPOTMipmaps;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

