/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTMapVec.h"

/**
 * A double precision map position defined using three coordinates. X and y coordinates denote positions on the map,<br>
 * while z coordinate is height from the ground plane. Actual units for x, y and z depend on map projection.<br>
 * For example, in EPSG:4326 x is used for latitude, y for longitude and z for height in meters.
 */
__attribute__ ((visibility("default"))) @interface NTMapPos : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a MapPos object. All coordinates will be 0.
 */
-(id)init;
/**
 * Constructs a MapPos object from 2 coordinates. The z coordinate will be 0.<br>
 * @param x The x coordinate.<br>
 * @param y The y coordinate.
 */
-(id)initWithX: (double)x y: (double)y;
/**
 * Constructs a MapPos object from 3 coordinates.<br>
 * @param x The x coordinate.<br>
 * @param y The y coordinate.<br>
 * @param z The z coordinate.
 */
-(id)initWithX: (double)x y: (double)y z: (double)z;
/**
 * Returns the x coordinate of this map position.<br>
 * @return The x coordinate of this map position.
 */
-(double)getX;
/**
 * Returns the y coordinate of this map position.<br>
 * @return The y coordinate of this map position.
 */
-(double)getY;
/**
 * Returns the z coordinate of this map position.<br>
 * @return The z coordinate of this map position.
 */
-(double)getZ;
/**
 * Creates a new map position by adding a map vector to this map position.<br>
 * @param v The map vector to be added.<br>
 * @return The new map position.
 */
-(NTMapPos*)add: (NTMapVec*)v;
/**
 * Creates a new map position by subtracting a map vector from this map position.<br>
 * @param v The map vector to be subtracted.<br>
 * @return The new map position.
 */
-(NTMapPos*)subVec: (NTMapVec*)v;
/**
 * Creates a new map vector by subtracting a map position from this map position.<br>
 * @param p The map position to be subtracted.<br>
 * @return The new map vector.
 */
-(NTMapVec*)subPos: (NTMapPos*)p;
/**
 * Checks for equality between this and another map position.<br>
 * @param p The other map position.<br>
 * @return True if equal.
 */
-(BOOL)isEqualInternal: (NTMapPos*)p;
/**
 * Calculates the distance between this and another map position.<br>
 * @param p The other map position.<br>
 * @return The distance between the two points.
 */
-(double)distanceFromPoint: (NTMapPos*)p;
/**
 * Calculates the square distance between this and another map position.<br>
 * @param p The other map position.<br>
 * @return The square distance between the two points.
 */
-(double)distanceSqrFromPoint: (NTMapPos*)p;
/**
 * Calculates the distance between this map position and an infinte line defined by two points.<br>
 * @param a Some point on the infinte line.<br>
 * @param b Another point on the infinite line.<br>
 * @return The distance between this map position and the infinite line.
 */
-(double)distanceFromLine: (NTMapPos*)a b: (NTMapPos*)b;
/**
 * Calculates the square distance between this map position and an infinte line defined by two points.<br>
 * @param a Some point on the infinte line.<br>
 * @param b Another point on the infinite line.<br>
 * @return The square distance between this map position and the infinite line.
 */
-(double)distanceSqrFromLine: (NTMapPos*)a b: (NTMapPos*)b;
/**
 * Calculates the distance between this map position and a line segment.<br>
 * @param a Starting coordinate of the line segment.<br>
 * @param b Ending coordinate of the line segment.<br>
 * @return The distance between this map position and the line segment.
 */
-(double)distanceFromLineSegment: (NTMapPos*)a b: (NTMapPos*)b;
/**
 * Calculates the square distance between this map position and a line segment.<br>
 * @param a Starting coordinate of the line segment.<br>
 * @param b Ending coordinate of the line segment.<br>
 * @return The square distance between this map position and the line segment.
 */
-(double)distanceSqrFromLineSegment: (NTMapPos*)a b: (NTMapPos*)b;
/**
 * Calculates the nearest point from this map position on a line segment.<br>
 * @param a Starting coordinate of the line segment.<br>
 * @param b Ending coordinate of the line segment.<br>
 * @return The nearest point from this map position that lies on the line segment.
 */
-(NTMapPos*)nearestPointOnLineSegment: (NTMapPos*)a b: (NTMapPos*)b;
/**
 * Creates a new map position by rotating this map position around the z axis by an angle.<br>
 * @param sin The sine value of the rotation angle.<br>
 * @param cos The cosine value of the rotation angle.<br>
 * @return The new rotated map position.
 */
-(NTMapPos*)getRotated2D: (double)sin cos: (double)cos;
/**
 * Returns the hash value of this object.<br>
 * @return The hash value of this object.
 */
-(int)hashInternal;
/**
 * Creates a string representation of this map position, useful for logging.<br>
 * @return The string representation of this map position.
 */
-(NSString*)description;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

