/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

typedef NS_ENUM(NSInteger, NTQuadTreeRootType) {
  NT_LEFT = -1,
  NT_CENTER = 0,
  NT_RIGHT = 1
};

typedef NS_ENUM(NSInteger, NTQuadTreeNodeType) {
  NT_ROOT = 0,
  NT_TOP_LEFT = 0,
  NT_TOP_RIGHT = 1,
  NT_BOTTOM_LEFT = 2,
  NT_BOTTOM_RIGHT = 3
};


#import "NTMapBounds.h"
#import "NTMapPos.h"
#import "NTMapTile.h"

__attribute__ ((visibility("default"))) @interface NTMapTileQuadTreeNode : NTMapTile
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)initWithX: (int)x y: (int)y zoom: (int)zoom frameNr: (int)frameNr;
-(id)initWithRootType: (enum NTQuadTreeRootType)rootType frameNr: (int)frameNr;
-(id)initWithParent: (NTMapTileQuadTreeNode*)parent nodeType: (enum NTQuadTreeNodeType)nodeType;
-(void)setFrameNr: (int)frameNr;
-(NTMapPos*)getCenter;
-(NTMapBounds*)getTileBounds;
-(double)getDistanceFromCamera;
-(void)setDistanceFromCamera: (double)distance;
-(float)getRadius;
-(NTMapTileQuadTreeNode*)getTopLeftChild;
-(NTMapTileQuadTreeNode*)getTopRightChild;
-(NTMapTileQuadTreeNode*)getBottomRightChild;
-(NTMapTileQuadTreeNode*)getBottomLeftChild;
-(NTMapTileQuadTreeNode*)getParent;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

