/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTNMLModelLODTreeDataSource.h"
#import "NTLayer.h"

/**
 * An advanced layer for 3D models that supports automatic Level of Detail (LOD) calculation based on view.<br>
 * Should be used together with corresponding data source.
 */
__attribute__ ((visibility("default"))) @interface NTNMLModelLODTreeLayer : NTLayer
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

+(NTNMLModelLODTreeLayer*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a NMLModelLODTreeLayer object from a data source.<br>
 * @param dataSource The data source from which this layer loads data.
 */
-(id)initWithDataSource: (NTNMLModelLODTreeDataSource*)dataSource;
/**
 * Returns the data source of this layer.<br>
 * @return The data source that was bound to this vector layer on construction.
 */
-(NTNMLModelLODTreeDataSource*)getDataSource;
/**
 * Set memory usage constraints for the layer. The specified limit is not exact, <br>
 * but should be relatively close to the actual memory usage of the layer.<br>
 * If specific view requires more data than specified limit, then lower LOD levels<br>
 * of the models are used. The default is 40MB.<br>
 * @param size The memory limit in bytes.
 */
-(void)setMaxMemorySize: (unsigned long)size;
/**
 * Set relative model LOD resolution. Higher values than 1 result in higher details <br>
 * (but slower performance and higher memory usage), while lower values give better <br>
 * performance but lower quality. The default is 1.<br>
 * @param factor The relative LOD resolution factor.
 */
-(void)setLODResolutionFactor: (float)factor;
-(BOOL)isUpdateInProgress;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
-(NSString*)swigGetClassName;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

