/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTVectorTileLayer.h"

/**
 * Specialized online vector tile layer that connects to Nutiteq online tile server.<br>
 * This layer is intended as a 'shortcut' to make using Nutiteq online service and<br>
 * vector tiles as simple as possible.
 */
__attribute__ ((visibility("default"))) @interface NTNutiteqOnlineVectorTileLayer : NTVectorTileLayer
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 */
+(NTNutiteqOnlineVectorTileLayer*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a NutiteqOnlineVectorTileLayer object from a style asset name.<br>
 * Uses "nutiteq.osm" as a source.<br>
 * Style asset must be included in the project, style asset defines visual style of the map.<br>
 * @param styleAssetName The name of the style asset that defines visual style of the map.
 */
-(id)initWithStyleAssetName: (NSString*)styleAssetName;
/**
 * Constructs a NutiteqOnlineVectorTileLayer object from a source name and style asset name.<br>
 * Style asset must be included in the project, style asset defines visual style of the map.<br>
 * @param source The tile source name. Main and default source is currently "nutiteq.osm".<br>
 * @param styleAssetName The name of the style asset that defines visual style of the map.
 */
-(id)initWithSource: (NSString*)source styleAssetName: (NSString*)styleAssetName;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

