/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * Tile status.
 */
typedef NS_ENUM(NSInteger, NTPackageTileStatus) {
/**
 * Tile is not part of the package.
 */
  NT_PACKAGE_TILE_STATUS_MISSING,
/**
 * Tile is part of the package, but package does not fully cover it.
 */
  NT_PACKAGE_TILE_STATUS_PARTIAL,
/**
 * Tile if part of the package and package fully covers it.
 */
  NT_PACKAGE_TILE_STATUS_FULL
};

/**
 * Information about map package. This includes id, version, name, description and size.
 */
__attribute__ ((visibility("default"))) @interface NTPackageTileMask : NSObject
{
  void *swigCPtr;
  BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Returns the encoded tile mask value. This should not be displayed to the user.<br>
 * @return The tile mask of the package
 */
-(NSString*)getStringValue;
/**
 * Returns the status of the specified tile. This method can be used for fast testing whether a tile is part of the package.<br>
 * @param zoom The zoom level of the tile.<br>
 * @param x The x coordinate of the tile.<br>
 * @param y The y coordinate of the tile.<br>
 * @return The status of the specified tile.
 */
-(enum NTPackageTileStatus)getTileStatus: (int)zoom x: (int)x y: (int)y;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

