/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTColor.h"
#import "NTBillboardStyle.h"

/**
 * A style for popups. Contains attributes for configuring how the popup is drawn on the screen.
 */
__attribute__ ((visibility("default"))) @interface NTPopupStyle : NTBillboardStyle
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

+(NTPopupStyle*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a PopupStyle object from various parameters. Instantiating the object directly is<br>
 * not recommended, PopupStyleBuilder should be used instead.<br>
 * @param color The color for the popup.<br>
 * @param attachAnchorPointX The horizontal attaching anchor point for the popup.<br>
 * @param attachAnchorPointY The vertical attaching anchor point for the popup.<br>
 * @param causesOverlap The causes overlap flag for the popup.<br>
 * @param hideIfOverlapped The hide if overlapped flag for the popup.<br>
 * @param horizontalOffset The horizontal offset for the popup.<br>
 * @param verticalOffset The vertical offset for the popup.<br>
 * @param placementPriority The placement priority for the popup.<br>
 * @param scaleWithDPI The scale with DPI flag for the label.
 */
-(id)initWithColor: (NTColor*)color attachAnchorPointX: (float)attachAnchorPointX attachAnchorPointY: (float)attachAnchorPointY causesOverlap: (BOOL)causesOverlap hideIfOverlapped: (BOOL)hideIfOverlapped horizontalOffset: (float)horizontalOffset verticalOffset: (float)verticalOffset placementPriority: (int)placementPriority scaleWithDPI: (BOOL)scaleWithDPI;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

