/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

__attribute__ ((visibility("default"))) @interface NTStringMap : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;
-(id)initWithArg0: (NTStringMap*)arg0;
-(unsigned int)size;
-(BOOL)empty;
-(void)clear;
-(NSString*)get: (NSString*)key;
-(void)set: (NSString*)key x: (NSString*)x;
-(void)del: (NSString*)key;
-(BOOL)has_key: (NSString*)key;
-(NSString*)get_key: (unsigned int)idx;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

