/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTColor.h"
#import "NTBitmap.h"
#import "NTLabelStyleBuilder.h"
#import "NTTextStyle.h"

/**
 * A builder class for TextStyle.
 */
__attribute__ ((visibility("default"))) @interface NTTextStyleBuilder : NTLabelStyleBuilder
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

+(NTTextStyleBuilder*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs a TextStyleBuilder object with all parameters set to defaults.
 */
-(id)init;
/**
 * Returns the font name for the text label.<br>
 * @return The platform dependent font name for the text label.
 */
-(NSString*)getFontName;
/**
 * Sets the font name for the text label.<br>
 * @param fontName The new platform dependent font name for the text label.
 */
-(void)setFontName: (NSString*)fontName;
/**
 * Returns the font size for the text label.<br>
 * @return The font size for the text label in points.
 */
-(int)getFontSize;
/**
 * Sets the font size for the text label.<br>
 * @param size The new font size for the text label in points.
 */
-(void)setFontSize: (int)size;
/**
 * Returns the stroke color for the text label.<br>
 * @return The stroke color for the text label.
 */
-(NTColor*)getStrokeColor;
/**
 * Sets the stroke color for the text label.<br>
 * @param strokeColor The new stroke color for the text label.
 */
-(void)setStrokeColor: (NTColor*)strokeColor;
/**
 * Returns the stroke width for the text label.<br>
 * @return The stroke width for the text label in screen density independent pixels.
 */
-(float)getStrokeWidth;
/**
 * Sets the stroke width for the text label.<br>
 * @param strokeWidth The new stroke width for the text label in screen density independent pixels.
 */
-(void)setStrokeWidth: (float)strokeWidth;
/**
 * Builds a new instance of the TextStyle object using previously set parameters.<br>
 * @return A new TextStyle object.
 */
-(NTTextStyle*)buildStyle;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
-(NSString*)swigGetClassName;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

