/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTUnsignedCharVector.h"

/**
 * A wrapper class for tile data.
 */
__attribute__ ((visibility("default"))) @interface NTTileData : NSObject
{
  void *swigCPtr;
  BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Constructs a TileData object from a data blob.<br>
 * @param data The source tile data.
 */
-(id)initWithData: (NTUnsignedCharVector*)data;
/**
 * Returns the maximum age of the tile data, tile data will expire after that point.<br>
 * @return Tile data maximum age in milliseconds, or -1 if the data does not expire.
 */
-(long long)getMaxAge;
/**
 * Sets the maximum age of tile data, tile data will expire after that point.<br>
 * 
 */
-(void)setMaxAge: (long long)age;
/**
 * Returns true if the tile should be replaced with parent tile.<br>
 * @return True if the tile should be replaced with parent. False otherwise.
 */
-(BOOL)isReplaceWithParent;
/**
 * Set the parent replacement flag.<br>
 * @param flag True when the tile should be replaced with the parent, false otherwise.
 */
-(void)setReplaceWithParent: (BOOL)flag;
/**
 * Returns tile data as a byte vector.<br>
 * @return Tile data as a byte vector.
 */
-(NTUnsignedCharVector*)getData;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

