/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "NTMapTile.h"
#import "NTTileData.h"
#import "NTProjection.h"

/**
 * Abstract base class for tile data sources. It provides default implementation <br>
 * for listener registration and other common tile data source methods.
 */
__attribute__ ((visibility("default"))) @interface NTTileDataSource : NSObject
{
  void *swigCPtr;
  BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**
 * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
 */
+(NTTileDataSource*)swigCreatePolymorphicInstance:(void*)cPtr swigOwnCObject:(BOOL)cMemoryOwn;

/**
 * Constructs an abstract TileDataSource object.<br>
 * Note: EPSG3857 projection is used.<br>
 * @param minZoom The minimum zoom level supported by this data source.<br>
 * @param maxZoom The maximum zoom level supported by this data source.
 */
-(id)initWithMinZoom: (int)minZoom maxZoom: (int)maxZoom;
/**
 * Returns the minimum zoom level supported by this data source.<br>
 * @return The minimum zoom level supported (inclusive).
 */
-(int)getMinZoom;
/**
 * Returns the maximum zoom level supported by this data source.<br>
 * @return The maximum zoom level supported (exclusive).
 */
-(int)getMaxZoom;
/**
 * Returns the projection of this tile source.<br>
 * @return The projection of this tile source.
 */
-(NTProjection*)getProjection;
/**
 * Loads the specified tile.<br>
 * @param tile The tile to load.<br>
 * @return The tile data. If the tile is not available, null may be returned.
 */
-(NTTileData*)loadTile: (NTMapTile*)tile;
/**
 * Notifies listeners that the tiles have changed. Action taken depends on the implementation of the<br>
 * listeners, but generally all cached tiles will be reloaded. If the removeTiles flag is set all caches will be cleared<br>
 * prior to reloading, if it's not set then the reloaded tiles will replace the old tiles in caches as they finish loading.<br>
 * @param removeTiles The remove tiles flag.
 */
-(void)notifyTilesChanged: (BOOL)removeTiles;
/**
 * Notifies listeners that the tiles have changed. Action taken depends on the implementation of the<br>
 * listeners, but generally all cached tiles will be reloaded. If the removeTiles flag is set all caches will be cleared<br>
 * prior to reloading, if it's not set then the reloaded tiles will replace the old tiles in caches as they finish loading.<br>
 * @param removeTiles The remove tiles flag.
 */
-(void)notifyTilesChangedSwigExplicitNTTileDataSource: (BOOL)removeTiles;
/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
-(NSString*)swigGetClassName;
/**
 * Returns the pointer to the connected director object. This is used internally by the SDK.<br>
 * @return The pointer to the connected director object or null if director is not connected.
 */
-(void *)swigGetDirectorObject;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

