/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * Possible drag modes.
 */
typedef NS_ENUM(NSInteger, NTVectorElementDragMode) {
/**
 * A single vertex is being moved.
 */
  NT_VECTOR_ELEMENT_DRAG_MODE_VERTEX,
/**
 * The whole vector element is being moved.
 */
  NT_VECTOR_ELEMENT_DRAG_MODE_ELEMENT
};


#import "NTMapPos.h"
#import "NTScreenPos.h"
#import "NTVectorElement.h"

/**
 * A container class that provies information about a dragging performed on<br>
 * a vector element or vector element vertex.
 */
__attribute__ ((visibility("default"))) @interface NTVectorElementDragInfo : NSObject
{
  void *swigCPtr;
  BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

/**  
 * Checks if this object is equal to the specified object.
 * @return True when objects are equal, false otherwise.
 */
-(BOOL)isEqual:(id)object;

/**
 * Returns the hash value of this object.
 * @return The hash value of this object.
 */
-(NSUInteger)hash;

/**
 * Returns the drag mode.<br>
 * @return The drag mode.
 */
-(enum NTVectorElementDragMode)getDragMode;
/**
 * Returns the drag position in screen coordinates.<br>
 * @return The drag position in screen coordinates.
 */
-(NTScreenPos*)getScreenPos;
/**
 * Returns the drag position in projection coordinate system of the layer.<br>
 * @return The drag position in projection coordinate system of the layer.
 */
-(NTMapPos*)getMapPos;
/**
 * Returns the vector element being dragged.<br>
 * @return The vector element being dragged.
 */
-(NTVectorElement*)getVectorElement;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

