/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * A diagnostic log for various SDK events.
 */
__attribute__ ((visibility("default"))) @interface NTLog : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Enables or disables writing error messages to the log.<br>
 * @param showError If true, then error messages will be written to the log.
 */
+(void)SetShowError: (BOOL)showError;
/**
 * Enables or disables writing warning messages to the log.<br>
 * @param showWarn If true, then warning messages will be written to the log.
 */
+(void)SetShowWarn: (BOOL)showWarn;
/**
 * Enables or disables writing info messages to the log.<br>
 * @param showInfo If true, then info messages will be written to the log.
 */
+(void)SetShowInfo: (BOOL)showInfo;
/**
 * Enables or disables writing internal debug messages to the log.<br>
 * @param showDebug If true, then debug messages will be written to the log.
 */
+(void)SetShowDebug: (BOOL)showDebug;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

