/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "LocalVectorDataSource_proxy.h"

/**
 * A modifiable vector data source that keeps all the elements in the local memory.<br>
 * The vector elements are kept in a k-d tree structure and only the visible elements get rendererd. <br>
 * There can be a small delay before previously invisible elements become visible after view changes.<br>
 * This makes it suitable for cases where there are a large number of static vector elements.<br>
 * <br>
 * The draw order of vector elements within the data source is undefined.<br>
 * @deprecated This class is deprecated, use LocalVectorDataSource directly.
 */
@interface NTKDTreeVectorDataSource : NTLocalVectorDataSource
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs an KDTreeVectorDataSource object.<br>
 * @param projection The projection used by this data source.
 */
-(id)initWithProjection: (NTProjection*)projection;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

