/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

enum QuadTreeRootType {
  LEFT = -1,
  CENTER = 0,
  RIGHT = 1
};

enum QuadTreeNodeType {
  ROOT = 0,
  TOP_LEFT = 0,
  TOP_RIGHT = 1,
  BOTTOM_LEFT = 2,
  BOTTOM_RIGHT = 3
};


#import "MapBounds_proxy.h"
#import "MapPos_proxy.h"
#import "MapTile_proxy.h"

@interface NTMapTileQuadTreeNode : NTMapTile
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)initWithX: (int)x y: (int)y zoom: (int)zoom frameNr: (int)frameNr;
-(id)initWithRootType: (enum QuadTreeRootType)rootType frameNr: (int)frameNr;
-(id)initWithParent: (NTMapTileQuadTreeNode*)parent nodeType: (enum QuadTreeNodeType)nodeType;
-(void)setFrameNr: (int)frameNr;
-(NTMapPos*)getCenter;
-(NTMapBounds*)getTileBounds;
-(double)getDistanceFromCamera;
-(void)setDistanceFromCamera: (double)distance;
-(float)getRadius;
-(NTMapTileQuadTreeNode*)getTopLeftChild;
-(NTMapTileQuadTreeNode*)getTopRightChild;
-(NTMapTileQuadTreeNode*)getBottomRightChild;
-(NTMapTileQuadTreeNode*)getBottomLeftChild;
-(NTMapTileQuadTreeNode*)getParent;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

