/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Tuple3D_proxy.h"

/**
 * A double precision map vector defined by 3 coordinates.
 */
@interface NTMapVec : NTTuple3D
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a MapVec object. All coordinates will be 0.
 */
-(id)init;
/**
 * Constructs a MapVec object from 2 coordinates. The z coordinate will be 0.<br>
 * @param x The x coordinate.<br>
 * @param y The y coordinate.
 */
-(id)initWithX: (double)x y: (double)y;
/**
 * Constructs a MapVec object from 3 coordinates.<br>
 * @param x The x coordinate.<br>
 * @param y The y coordinate.<br>
 * @param z The z coordinate.
 */
-(id)initWithX: (double)x y: (double)y z: (double)z;
/**
 * Adds another map vector to this map vector.<br>
 * @param v The map vector to be added.<br>
 * @return This map vector after the addition.
 */
-(NTMapVec*)addThis: (NTMapVec*)v;
/**
 * Subtracts another map vector from this map vector.<br>
 * @param v The map vector to be added.<br>
 * @return This map vector after the subtraction.
 */
-(NTMapVec*)subThis: (NTMapVec*)v;
/**
 * Multiplies this map vector by a multiplier.<br>
 * @param multiplier The multiplier.<br>
 * @return This map vector after the multiplication.
 */
-(NTMapVec*)mulThis: (double)multiplier;
/**
 * Divides this map vector by a divider.<br>
 * @param divider The divider.<br>
 * @return This map vector after the division.
 */
-(NTMapVec*)divThis: (double)divider;
/**
 * Creates a new map vector by adding a map vector to this map vector.<br>
 * @param v The map vector to be added.<br>
 * @return The new map vector.
 */
-(NTMapVec*)add: (NTMapVec*)v;
/**
 * Creates a new map vector by subtracting a map vector from this map vector.<br>
 * @param v The map vector to be subtracted.<br>
 * @return The new map vector.
 */
-(NTMapVec*)sub: (NTMapVec*)v;
/**
 * Creates a new map vector by multiplying this map vector with a multiplier.<br>
 * <br>
 * @return The new map vector.
 */
-(NTMapVec*)mul: (double)multiplier;
/**
 * Creates a new map vector by dividing this map vector with a divider.<br>
 * <br>
 * @return The new map vector.
 */
-(NTMapVec*)div: (double)divider;
/**
 * Checks for equality between this and another map vector.<br>
 * <br>
 * @return True if equal.
 */
-(BOOL)equals: (NTMapVec*)v;
/**
 * Checks for inequality between this and another map vector.<br>
 * <br>
 * @return True if not equal.
 */
-(BOOL)differs: (NTMapVec*)v;
/**
 * Calculates the length of this map vector.<br>
 * @return The length of this map vector.
 */
-(double)length;
/**
 * Calculates the square length of this map vector.<br>
 * @return The square length of this map vector.
 */
-(double)lengthSqr;
/**
 * Normalizes this map vector.<br>
 * @return This map vector after the normalization.
 */
-(NTMapVec*)normalize;
/**
 * Creates a new map vector by normalizing this map vector.<br>
 * @return The new normalized map vector.
 */
-(NTMapVec*)getNormalized;
/**
 * Rotates this map vector around it's back end and around z axis.<br>
 * @param sin The sine value of the rotation angle.<br>
 * @param cos The cosine value of the rotation angle.<br>
 * @return This map vector after the rotation.
 */
-(NTMapVec*)rotate2D: (double)sin cos: (double)cos;
/**
 * Creates a new map vector by rotating this map vector around it's back end and around z axis.<br>
 * @param sin The sine value of the rotation angle.<br>
 * @param cos The cosine value of the rotation angle.<br>
 * @return The new rotated map vector.
 */
-(NTMapVec*)getRotated2D: (double)sin cos: (double)cos;
/**
 * Calculates the 2D cross product between this and another map vector. Defined as x1 * y2 - y1 * x2.<br>
 * @param v The other map vector.<br>
 * @return The 2D cross product between this and another map vector.
 */
-(double)crossProduct2D: (NTMapVec*)v;
/**
 * Creates a new map vector that's perpendicular to the plane defined by this and another map vector.<br>
 * @param v The other map vector.<br>
 * @return The new perpendicular map vector.
 */
-(NTMapVec*)crossProduct3D: (NTMapVec*)v;
/**
 * Calculates the dot product between this and another map vector.<br>
 * @param v The other map vector.<br>
 * @return The dot product between this and another map vector.
 */
-(double)dotProduct: (NTMapVec*)v;
/**
 * Creates a string representation of this map vector, useful for logging.<br>
 * @return The string representation of this map vector.
 */
-(NSString*)toString;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

