/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Billboard_proxy.h"
#import "MarkerStyle_proxy.h"

/**
 * A billboard element with a static bitmap that can be displayed on the map.
 */
@interface NTMarker : NTBillboard
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a Marker object with the specified style and attaches it to a billboard element.<br>
 * @param baseBillboard The billboard this billboard will be attached to.<br>
 * @param style The style that defines what this marker looks like.
 */
-(id)initWithBaseBillboard: (NTBillboard*)baseBillboard style: (NTMarkerStyle*)style;
/**
 * Constructs a Marker object from a geometry object and a style.<br>
 * @param geometry The geometry object that defines the location of this marker.<br>
 * @param style The style that defines what this marker looks like.
 */
-(id)initWithGeometry: (NTPointGeometry*)geometry style: (NTMarkerStyle*)style;
/**
 * Constructs a Marker object from a map position and a style.<br>
 * <br>
 * @param style The style that defines what this marker looks like.
 */
-(id)initWithPos: (NTMapPos*)pos style: (NTMarkerStyle*)style;
/**
 * Returns the style of this marker.<br>
 * @return The style that defines what this marker looks like.
 */
-(NTMarkerStyle*)getStyle;
/**
 * Sets the style for this marker.<br>
 * @return The new style that defines what this marker looks like.
 */
-(void)setStyle: (NTMarkerStyle*)style;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

