/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "UnsignedCharVector_proxy.h"

/**
 * Style set for MapBox vector tiles. Style set is a read-only key-value containers,<br>
 * their contents should not be read or used at application level.
 */
@interface NTMBVectorTileStyleSet : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a styleset from byte vector.<br>
 * @param data Opaque byte vector describing the style set.
 */
-(id)initWithData: (UnsignedCharVector*)data;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

