/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "UnsignedCharVector_proxy.h"
#import "VectorTileDecoder_proxy.h"
#import "MBVectorTileStyleSet_proxy.h"

/**
 * Decoder for vector tiles in MapBox format.
 */
@interface NTMBVectorTileDecoder : NTVectorTileDecoder
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs decoder for MapBox vector tiles based on given style set.<br>
 * @param styleSet Style set for the tiles.
 */
-(id)initWithStyleSet: (NTMBVectorTileStyleSet*)styleSet;
/**
 * Updates relative scale of geometry elements (lines). Default is 1.0f.<br>
 * Warning: changing this value may corrupt map appearance.<br>
 * @param scale New relative scale (1.0f is the default).
 */
-(void)setGeometryScale: (float)scale;
/**
 * Updates the relative scale of billboard and text elements. Default is 1.0f.<br>
 * Warning: changing this value may corrupt map appearance.<br>
 * @param scale New relative scale (1.0f is the default).
 */
-(void)setBillboardScale: (float)scale;
-(NTColor*)getBackgroundColor;
-(int)getMinZoom;
-(int)getMaxZoom;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

