/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "VectorTileLayer_proxy.h"

/**
 * Specialized online vector tile layer that connects to Nutiteq online tile server.<br>
 * This layer is intended as a 'shortcut' to make using Nutiteq online service and vector tiles as simple as possible.
 */
@interface NTNutiteqOnlineVectorTileLayer : NTVectorTileLayer
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a NutiteqOnlineVectorTileLayer object from a registered API key and a style asset name.<br>
 * Style asset must be included in the project, style asset defines visual style of the map.<br>
 * @param apiKey The registered API key for the app.<br>
 * @param styleAssetName The name of the style asset that defines visual style of the map.
 */
-(id)initWithApiKey: (NSString*)apiKey styleAssetName: (NSString*)styleAssetName;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

