/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Bitmap_proxy.h"
#import "Style_proxy.h"

/**
 * A style for points. Contains attributes for configuring how the point is drawn on the screen.
 */
@interface NTPointStyle : NTStyle
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a PointStyle object from various parameters. Instantiating the object directly is<br>
 * not recommended, PointStyleBuilder should be used instead.<br>
 * @param color The color for the point.<br>
 * @param bitmap The bitmap for the point.<br>
 * @param clickSize The size of the point used for click detection.<br>
 * @param size The size for the point.
 */
-(id)initWithColor: (NTColor*)color bitmap: (NTBitmap*)bitmap clickSize: (float)clickSize size: (float)size;
/**
 * Returns the bitmap of the point.<br>
 * @return The bitmap of the point.
 */
-(NTBitmap*)getBitmap;
/**
 * Returns the size of the point used for click detection.<br>
 * @return The size of the point used for click detection.
 */
-(float)getClickSize;
/**
 * Returns the size of the point.<br>
 * @return The size of the point.
 */
-(float)getSize;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

