/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "PolygonStyle_proxy.h"
#import "StyleBuilder_proxy.h"

/**
 * A builder class for PolygonStyle.
 */
@interface NTPolygonStyleBuilder : NTStyleBuilder
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a PolygonStyleBuilder object with all parameters set to defaults.
 */
-(id)init;
/**
 * Returns the bitmap of the point.<br>
 * @return The bitmap of the point.<br>
 * <br>
 * Sets the bitmap that will be used for drawing the polygon. The image will be repeated <br>
 * vertically and horizontally to cover the polygon. The default is "default_polygon.png"<br>
 * <br>
 * <br>
 * Returns the line style of the edges of the polygon.<br>
 * @return The line style of the edges of the polygon. May be null.
 */
-(NTLineStyle*)getLineStyle;
/**
 * Sets the line style that will be used to draw the edges of the polygon. If null is passed<br>
 * no edges will be drawn. The default is null.<br>
 * @param lineStyle The new style for the edges of the polygon.
 */
-(void)setLineStyle: (NTLineStyle*)lineStyle;
/**
 * Builds a new instance of the PolygonStyle object using previously set parameters.<br>
 * @return A new PolygonStyle object.
 */
-(NTPolygonStyle*)buildStyle;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

