/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "PolygonGeometry_proxy.h"
#import "PolygonStyle_proxy.h"
#import "VectorElement_proxy.h"

/**
 * A geometric polygon that can be displayed on the map.<br>
 * Polygons can be concave and have multiple overlapping holes.
 */
@interface NTPolygon : NTVectorElement
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a Polygon object from a geometry object and a style.<br>
 * @param geometry The geometry object that defines the location and holes of this polygon.<br>
 * @param style The style that defines what this polygon looks like.
 */
-(id)initWithGeometry: (NTPolygonGeometry*)geometry style: (NTPolygonStyle*)style;
/**
 * Constructs a Polygon object from a vector of map positions and a style.<br>
 * @param poses The vector of map positions that defines the location of this polygon.<br>
 * @param style The style that defines what this polygon looks like.
 */
-(id)initWithPoses: (MapPosVector*)poses style: (NTPolygonStyle*)style;
/**
 * Constructs a Polygon object from a vector of map positions, a vector of holes and a style.<br>
 * @param poses The vector of map positions that defines the location of this polygon.<br>
 * @param holes The vector of holes that defines the locations of holes of this polygon.<br>
 * @param style The style that defines what this polygon looks like.
 */
-(id)initWithPoses: (MapPosVector*)poses holes: (MapPosVectorVector*)holes style: (NTPolygonStyle*)style;
-(NTPolygonGeometry*)getGeometry;
/**
 * Sets the location for this polygon.<br>
 * @param geometry The new geometry object that defines the location and holes of this polygon.
 */
-(void)setGeometry: (NTPolygonGeometry*)geometry;
/**
 * Sets the location for this polygon.<br>
 * @param poses The new vector of map positions that define the location of this polygon.
 */
-(void)setPoses: (MapPosVector*)poses;
/**
 * Sets the location and holes for this polygon.<br>
 * @param poses The new vector of map positions that defines the location of this polygon.<br>
 * @param holes The new vector of holes that defines the locations of holes of this polygon.
 */
-(void)setPoses: (MapPosVector*)poses holes: (MapPosVectorVector*)holes;
/**
 * Returns the style of this polygon.<br>
 * @return The style that defines what this polygon looks like.
 */
-(NTPolygonStyle*)getStyle;
/**
 * Sets the style for this polygon.<br>
 * @param style The new style that defines what this polygon looks like.
 */
-(void)setStyle: (NTPolygonStyle*)style;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

