/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Style_proxy.h"

/**
 * A style for 3d polygons. Contains attributes for configuring how the 3d polygon is drawn on the screen.
 */
@interface NTPolygon3DStyle : NTStyle
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a Polygon3DStyle object from various parameters. Instantiating the object directly is<br>
 * not recommended, Polygon3DStyleBuilder should be used instead.<br>
 * @param color The color for the 3d polygon.
 */
-(id)initWithColor: (NTColor*)color;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

