/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Geometry_proxy.h"
#import "MapPosVectors_proxy.h"

@interface NTPolygonGeometry : NTGeometry
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)initWithPoses: (MapPosVector*)poses;
-(id)initWithPoses: (MapPosVector*)poses holes: (MapPosVectorVector*)holes;
-(MapPosVector*)getPoses;
-(MapPosVectorVector*)getHoles;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

