/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Polygon3DStyle_proxy.h"
#import "StyleBuilder_proxy.h"

/**
 * A builder class for Polygon3DStyle.
 */
@interface NTPolygon3DStyleBuilder : NTStyleBuilder
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a Polygon3DStyleBuilder object with all parameters set to defaults.
 */
-(id)init;
/**
 * Builds a new instance of the Polygon3DStyle object using previously set parameters.<br>
 * @return A new Polygon3DStyle object.
 */
-(NTPolygon3DStyle*)buildStyle;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

