/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "BillboardStyleBuilder_proxy.h"
#import "PopupStyle_proxy.h"

/**
 * A builder class for PopupStyle.
 */
@interface NTPopupStyleBuilder : NTBillboardStyleBuilder
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a PopupStyleBuilder object with all parameters set to defaults.
 */
-(id)init;
/**
 * Builds a new instance of the PopupStyle object using previously set parameters.<br>
 * @return A new PopupStyle object.
 */
-(NTPopupStyle*)buildStyle;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

