/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Bitmap_proxy.h"
#import "UnsignedCharVector_proxy.h"

/**
 * A wrapper class for bitmaps representing raster map tiles.
 */
@interface NTRasterTileBitmap : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a RasterTileBitmap object from an uncompressed bitmap.<br>
 * @param bitmap The source bitmap for this raster tile bitmap.
 */
-(id)initWithBitmap: (NTBitmap*)bitmap;
/**
 * Constructs a RasterTileBitmap object from a compressed image.<br>
 * 
 */
-(id)initWithCompressed: (UnsignedCharVector*)compressed;
/**
 * Returns the source bitmap.<br>
 * @return The source bitmap.
 */
-(NTBitmap*)getBitmap;
/**
 * Returns this raster tile bitmap as a compressed byte vector.<br>
 * @return The compressed bitmap as a byte vector.
 */
-(UnsignedCharVector*)getCompressed;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

