/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Color_proxy.h"

/**
 * A base class for other StyleBuilder subclasses.
 */
@interface NTStyleBuilder : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Copy constructs style builder from another style builder.<br>
 * @param styleBuilder The other style builder.
 */
-(id)initWithStyleBuilder: (NTStyleBuilder*)styleBuilder;
/**
 * Copies the other style builder's parameters to this one.<br>
 * @param styleBuilder The other style builder.<br>
 * @return This style builder.
 */
-(NTStyleBuilder*)clone: (NTStyleBuilder*)styleBuilder;
/**
 * Returns the color of the vector element.<br>
 * @return The color of the vector element.
 */
-(NTColor*)getColor;
/**
 * Sets the color for the vector element. Coloring works by multiplying the bitmap<br>
 * of the vector element with the specified color. If the color is set to white, the resulting bitmap<br>
 * will look exactly like the original. The default is white.<br>
 * @param color The new color for the vector element.
 */
-(void)setColor: (NTColor*)color;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

