/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Bitmap_proxy.h"
#import "Label_proxy.h"
#import "TextStyle_proxy.h"

/**
 * A text element that can be displayed on the map.
 */
@interface NTText : NTLabel
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a Text object with the specified style and attaches it to a billboard element.<br>
 * @param baseBillboard The billboard this text label will be attached to.<br>
 * @param style The style that defines what this text label looks like.<br>
 * @param text The text to be displayed.
 */
-(id)initWithBaseBillboard: (NTBillboard*)baseBillboard style: (NTTextStyle*)style text: (NSString*)text;
/**
 * Constructs a Text object from a geometry object and a style.<br>
 * @param geometry The geometry object that defines the location of this text label.<br>
 * @param style The style that defines what this text label looks like.<br>
 * @param text The text to be displayed.
 */
-(id)initWithGeometry: (NTPointGeometry*)geometry style: (NTTextStyle*)style text: (NSString*)text;
/**
 * Constructs a Text object from a map position and a style.<br>
 * <br>
 * @param style The style that defines what this text label looks like.<br>
 * @param text The text to be displayed.
 */
-(id)initWithPos: (NTMapPos*)pos style: (NTTextStyle*)style text: (NSString*)text;
-(NTBitmap*)drawBitmap: (float)dpToPX;
/**
 * Returns the display text.<br>
 * @return The display text.
 */
-(NSString*)getText;
/**
 * Sets the display text.<br>
 * @param text The text to be displayed.
 */
-(void)setText: (NSString*)text;
/**
 * Returns the style of this text label.<br>
 * @return The style that defines what this text label looks like.
 */
-(NTBillboardStyle*)getStyle;
/**
 * Sets the style for this text label.<br>
 * @return The new style that defines what this text label looks like.
 */
-(void)setStyle: (NTTextStyle*)style;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

