/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "Color_proxy.h"
#import "LabelStyleBuilder_proxy.h"
#import "TextStyle_proxy.h"

/**
 * A builder class for TextStyle.
 */
@interface NTTextStyleBuilder : NTLabelStyleBuilder
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Constructs a TextStyleBuilder object with all parameters set to defaults.
 */
-(id)init;
/**
 * Sets the font name for the text label.<br>
 * 
 */
-(void)setFontName: (NSString*)fontName;
/**
 * Sets the font size for the text label.<br>
 * 
 */
-(void)setFontSize: (int)size;
/**
 * Sets the stroke color for the text label.<br>
 * 
 */
-(void)setStrokeColor: (NTColor*)strokeColor;
/**
 * Sets the stroke width for the text label.<br>
 * 
 */
-(void)setStrokeWidth: (float)strokeWidth;
/**
 * Builds a new instance of the TextStyle object using previously set parameters.<br>
 * @return A new TextStyle object.
 */
-(NTTextStyle*)buildStyle;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

