/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * Possible tiles types.
 */
enum TilesType {
/**
 * Tiles that are visible on the screen.
 */
  TILES_TYPE_VISIBLE,
/**
 * Tiles that are not visible on the screen, but are right outside the visible frustum.
 */
  TILES_TYPE_PRELOADING,
/**
 * Both visible and preloading tiles.
 */
  TILES_TYPE_BOTH
};

/**
 * Abstract base class for tile data sources. It provides default implementation <br>
 * for listener registration and other common tile data source methods.
 */
@interface NTTileDataSource : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Returns the minimum zoom level supported by this data source.<br>
 * @return The minimum zoom level supported (inclusive).
 */
-(int)getMinZoom;
/**
 * Returns the maximum zoom level supported by this data source.<br>
 * @return The maximum zoom level supported (exclusive).
 */
-(int)getMaxZoom;
/**
 * Notifies listeners that the tiles have changed. Action taken depends on the implementation of the<br>
 * listeners, but generally all cached tiles will be reloaded. If the removeTiles flag is set all caches will be cleared<br>
 * prior to reloading, if it's not set then the reloaded tiles will replace the old tiles in caches as they finish loading.<br>
 * @param tilesType The type of tiles the event affects.<br>
 * @param removeTiles The remove tiles flag.
 */
-(void)notifyTilesChanged: (enum TilesType)tilesType removeTiles: (BOOL)removeTiles;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

