/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif

/**
 * An abstract base class for MapVec and MapPos.
 */
@interface NTTuple3D : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Returns the x coordinate of this tuple.<br>
 * @return The x coordinate of this tuple.
 */
-(double)getX;
/**
 * Sets the x coordinate of this tuple.<br>
 * @param x The new x coordinate of this tuple.
 */
-(void)setX: (double)x;
/**
 * Returns the y coordinate of this tuple.<br>
 * @return The y coordinate of this tuple.
 */
-(double)getY;
/**
 * Sets the y coordinate of this tuple.<br>
 * @param y The new y coordinate of this tuple.
 */
-(void)setY: (double)y;
/**
 * Returns the z coordinate of this tuple.<br>
 * @return The z coordinate of this tuple.
 */
-(double)getZ;
/**
 * Sets the z coordinate of this tuple.<br>
 * @param z The new z coordinate of this tuple.
 */
-(void)setZ: (double)z;
/**
 * Sets the x and y coordinates of this tuple.<br>
 * @param x The new x coordinate of this tuple.<br>
 * @param y The new y coordinate of this tuple.
 */
-(void)setCoordsWithX: (double)x y: (double)y;
/**
 * Sets the x, y and z coordinates of this tuple.<br>
 * @param x The new x coordinate of this tuple.<br>
 * @param y The new y coordinate of this tuple.<br>
 * @param z The new z coordinate of this tuple.
 */
-(void)setCoordsWithX: (double)x y: (double)y z: (double)z;
/**
 * An abstract method for creating a string representation of a this tuple, useful for logging.<br>
 * @return The string representation of this tuple.
 */
-(NSString*)toString;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

