/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>


#ifdef __cplusplus
extern "C" {
#endif


#import "MapPos_proxy.h"
#import "VectorElement_proxy.h"

/**
 * A container class that provies information about a click performed on<br>
 * a vector element.
 */
@interface NTVectorElementClickInfo : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
/**
 * Returns the click position.<br>
 * @return The click position in the coordinate system of the base projection.
 */
-(NTMapPos*)getClickPos;
/**
 * Returns the position on the clicked element, that is close to the click position.<br>
 * For points it will always be the center position, for lines it will be the closest point<br>
 * on the line, for billboards it will be the anchor point and for polygons it's equal to<br>
 * getClickPos().<br>
 * @return The element click position in the coordinate system of the base projection.
 */
-(NTMapPos*)getElementClickPos;
/**
 * Returns the distance from the vector element to the camera.<br>
 * @return The distance from the vector element to the camera in the internal coordiante system.
 */
-(double)getDistance;
/**
 * Returns the relative draw order of the vector element.<br>
 * @return The draw order of this vector element relative to others vector elements,<br>
 *         which where also clicked.
 */
-(unsigned int)getOrder;
/**
 * Returns the clicked vector element.<br>
 * @return The vector element on which the click was performed.
 */
-(NTVectorElement*)getVectorElement;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

